import type { Metadata } from "next"
import { Inter, Montserrat } from "next/font/google"

import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"

const inter = Inter({ subsets: ["latin"] })
const montserrat = Montserrat({ subsets: ["latin-ext"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <ClerkProvider>
        <body className={`${inter.className} ${montserrat.className}`}>{children}</body>
      </ClerkProvider>
    </html>
  )
}
